# Generated by Django 4.0.3 on 2022-03-21 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friendshiptest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ManyToManyField(to='friendshiptest.choice')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='friendshiptest.question')),
            ],
        ),
    ]
