# Generated by Django 4.0.3 on 2022-03-21 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friendshiptest', '0002_questionanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answered_ques', to='friendshiptest.question'),
        ),
    ]
