# Generated by Django 4.0.3 on 2022-03-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendshiptest', '0004_alter_choice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswers',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
