# Generated by Django 4.0.3 on 2022-03-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendshiptest', '0005_useranswers_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpaper',
            name='questions',
            field=models.ManyToManyField(to='friendshiptest.question'),
        ),
    ]
