# Generated by Django 4.0.3 on 2022-03-23 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friendshiptest', '0006_testpaper_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friendshiptest.choice')),
            ],
        ),
        migrations.RemoveField(
            model_name='useranswers',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='useranswers',
            name='question',
        ),
        migrations.RemoveField(
            model_name='useranswers',
            name='test_paper',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='que_choice',
            new_name='question_type',
        ),
        migrations.RemoveField(
            model_name='testpaper',
            name='questions',
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='name',
            field=models.CharField(choices=[('select', 'Single Select'), ('multiselect', 'Multiple Select')], default='select', max_length=15),
        ),
        migrations.AlterField(
            model_name='testpaper',
            name='submitted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='QuestionAnswer',
        ),
        migrations.DeleteModel(
            name='UserAnswers',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answered_ques', to='friendshiptest.question'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='test_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friendshiptest.testpaper'),
        ),
    ]
